name: 'Due Dates'
description: 'Manage due dates on issues'
author: 'Alex Leventer'
inputs:
  GH_TOKEN:
    description: GitHub token used to make API requests
    required: true
branding:
  icon: 'calendar'
  color: 'purple'
runs:
  using: 'node16'
  main: 'dist/app.js'
